### ISSUE TITLE
TomlDecodeError exception should include file position

### ISSUE THREAD

**Issue by mnp** [uiri/toml#100]
Things like "Duplicate keys" would be easier for end user to track down if the message included file char number, or line/column where detected.  This could be part of the exception string or a member on the exception class.

**Comment by kawing-chiu** [comment]
+1 for this. The exact line number and position should be included. I just tried to load the example in this repository:
```
toml.load('./example-v0.4.0.toml')
```
But got a very confusing error message:
```
TomlDecodeError: This float doesn't have a leading digit
```
And I have no way to identify where the problem is.

**Comment by mnp** [comment]
Here's another case, where

```
[foo]
bad = {xx="a", yy="b"}
```

raises `toml.TomlDecodeError: Stuff after closed string. WTF?`, which is nice. :-)
