### ISSUE TITLE
Toml fails to extract string

### ISSUE THREAD

**Issue by coulix** [uiri/toml#103]
This structure manages to get `CONTACT_US` but not `CONTACT_US_MESSAGE`. The `FR` value is empty.  

```
[CONTACT_US]
FR = [
    "Contacte-nous 📱",
]

[CONTACT_US_MESSAGE]
FR = [
    "Laisse moi un message je le ferai passer à mon équipe qui te répondra au plus vite {{ emojis.ok|random }}"
]
```

```
{'CONTACT_US': {'FR': ['Contacte-nous 📱']},  'CONTACT_US_MESSAGE': {'FR': []}}
```

Removing `{{ emojis.ok|random }}` helps. Is the issue the  `{{` ? **pytoml** managed to parse it.

**Comment by uiri** [comment]
Which version of `toml` are you using? It looks like this has been fixed since the latest release.
