### ISSUE TITLE
datetimes are serialized incorrectly

### ISSUE THREAD

**Issue by wimglenn** [uiri/toml#106]
Hi there, I can't use uiri/toml implementation because of this deal-breaker:

```
>>> from datetime import datetime
>>> tz = pytz.timezone('America/Chicago')
>>> dt_naive = datetime(2017, 6, 6, 12, 34, 56)
>>> dt_aware = tz.localize(dt_naive)
>>> d = {'dt': dt_aware}
>>> print(dt_aware)
2017-06-06 12:34:56-05:00
```

So, I have non-naive datetime in the data.  

```
>>> import toml
>>> toml.dumps(d)
'dt = 2017-06-06T12:34:56Z\n'
                         ^
                         |
                       UTC?!
```

The Z here indicates Zulu time; the serialized datetime is indicated as UTC.  Outputting a naive datetime would perhaps be understandable, but indicating an _incorrect_ timezone is really bad.  

Other libraries don't make this mistake:

```
>>> import pytoml
>>> pytoml.dumps(d)
'dt = 2017-06-06T12:34:56-5.00.0\n'
>>> import yaml
>>> yaml.dump(d)
"{dt: !!timestamp '2017-06-06 12:34:56-05:00'}\n"
```

**Comment by uiri** [comment]
Thank you for the bug report! It looks like the code ignored any timezone information attached to the datetime and just assumed Zulu time. This has been fixed in the latest development version.
