### ISSUE TITLE
Broken parsing within lists

### ISSUE THREAD

**Issue by jvrsantacruz** [uiri/toml#107]
After using toml very happily for most of our new applications and services, we seem to have hit a parsing bug for certain strings within lists.

```python
>>> toml.loads("""
ignored = [
    '\w{6}$'
]

broken = ['\w{6}$']

ok = [
    '\w\w\w\w\w\w$'
]
""")
{u'broken': [u'\\w{6'], u'ignored': [], u'ok': [u'\\w\\w\\w\\w\\w\\w$']}
```
As the example shows there are two errors. They seem to be escaping and white space related.

- The *ignored* list containing the `\w{6}` value is empty. Even with more elements in it, none gets in the list.
- The *broken* list conflictive string `\w{6}` is missing last two characters.

This fails consistently in *Python 2.7.12* and *Python 3.5.2*.
Used version is *toml (0.9.2)* which is the last one AFAIK.

**Comment by uiri** [comment]
This appears to be fixed in the latest development version.

Can you confirm?

**Comment by jvrsantacruz** [comment]
I can confirm this works for toml (7ec24e35db91f1e39ea07bf285fc6a06f77c7a79) installed locally using python 2.7:

```python
>>> toml.loads("""
ignored = [
    '\w{6}$'
]

broken = ['\w{6}$']

ok = [
    '\w\w\w\w\w\w$'
]
""")
{u'broken': [u'\\w{6}$'],
 u'ignored': [u'\\w{6}$'],
 u'ok': [u'\\w\\w\\w\\w\\w\\w$']}
```

:)

**Comment by uiri** [comment]
Alright, closing as fixed.

I'm well aware that this project is overdue for a bug fix release :)
