### ISSUE TITLE
Failure to decode an inline table with a string that has embedded square brackets

### ISSUE THREAD

**Issue by zackelan** [uiri/toml#109]
I'm not sure the issue headline captures it exactly, hopefully the examples below make it more clear. I think I narrowed it down to a corner case of a) an inline table; b) the inline table having more than one item; and c) one of the items in the table being a string with embedded square brackets.

Repro:

```
import toml

WORKING_TOMLS = [
"""
a = [
    {x = '1', y = 'no embedded brackets'},
]
""",

"""
a = [
    {x = '1', y = 'embedded {} brackets'},
]
""",

"""
a = [
    {y = 'embedded [] brackets'},
]
""",

"""
[[a]]
x = '1'
y = 'embedded [] brackets'
"""
]

BROKEN_TOML = """
a = [
    {x = '1', y = 'embedded [] brackets'},
]
"""

for working_toml in WORKING_TOMLS:
    print(toml.loads(working_toml))

print(toml.loads(BROKEN_TOML))

```

Expected:

```
{'a': [{'x': '1', 'y': 'no embedded brackets'}]}
{'a': [{'x': '1', 'y': 'embedded {} brackets'}]}
{'a': [{'y': 'embedded [] brackets'}]}
{'a': [{'x': '1', 'y': 'embedded [] brackets'}]}
{'a': [{'x': '1', 'y': 'embedded [] brackets'}]}
```

Actual:

```
{'a': [{'x': '1', 'y': 'no embedded brackets'}]}
{'a': [{'x': '1', 'y': 'embedded {} brackets'}]}
{'a': [{'y': 'embedded [] brackets'}]}
{'a': [{'x': '1', 'y': 'embedded [] brackets'}]}
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    print(toml.loads(BROKEN_TOML))
  File "/home/zack/test/venv/lib/python3.6/site-packages/toml.py", line 370, in loads
    multibackslash)
  File "/home/zack/test/venv/lib/python3.6/site-packages/toml.py", line 475, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "/home/zack/test/venv/lib/python3.6/site-packages/toml.py", line 634, in _load_value
    return (_load_array(v, _dict), "array")
  File "/home/zack/test/venv/lib/python3.6/site-packages/toml.py", line 737, in _load_array
    nval, ntype = _load_value(a[i], _dict)
  File "/home/zack/test/venv/lib/python3.6/site-packages/toml.py", line 637, in _load_value
    _load_inline_object(v, inline_object, _dict)
  File "/home/zack/test/venv/lib/python3.6/site-packages/toml.py", line 395, in _load_inline_object
    candidate_groups[0] = candidate_group + "," + candidate_groups[0]
IndexError: list index out of range
```

Environment:
- Discovered with Python 3.6.1 and toml 0.9.2
- Verified still reproducible with Python 3.6.1 and latest master branch of this repo
- Also reproducible on Python 2.7.13 (with both toml 0.9.2 and the master branch)

**Comment by jansegre** [comment]
I stumbled with this, but after reading the [oficial toml readme](https://github.com/toml-lang/toml#inline-table) I think this is not an error:

> No newlines are allowed between the curly braces unless they are valid within a value.

What could be done is trying to show a better error.

**Comment by zackelan** [comment]
I don't think that part of the spec applies here:

> Inline tables are intended to appear on a single line. No newlines are allowed between the curly braces unless they are valid within a value. Even so, it is strongly discouraged to break an inline table onto multiples lines. If you find yourself gripped with this desire, it means you should be using standard tables.

So I think what that forbids is this:

```
a = [
    {x = '1',
    y = '2'}
]
```

I think the relevant part of the spec for this bug is:

> Basic strings are surrounded by quotation marks. Any Unicode character may be used except those that must be escaped: quotation mark, backslash, and the control characters (U+0000 to U+001F).

Suggests to me that those square brackets are perfectly valid within a string, and it's a bug in the parser that it's rejected in this corner case.

**Comment by uiri** [comment]
Hi thanks for the bug report.

The issue appears to be related to having an array of inline tables and having one of those inline tables with multiple values and a string with square brackets inside.

This is permitted by the spec. The inline table may not have newlines but values inside the inline table may have newlines. In the examples here, the newlines are inside of the arrays which are permitted to have newlines.

Arrays have to be of a single type. So, in this case, they are arrays of inline tables which appears to be valid according to the spec since inline tables may contain inline tables as values.
