### ISSUE TITLE
Error parsing value with escaped quotes

### ISSUE THREAD

**Issue by jpotterm** [uiri/toml#110]
If I run this code:

```python
import toml

with open('test.toml', 'r') as f:
    toml_dict = toml.load(f)
    print(toml_dict)
```

On this file (test.toml):

```toml
test = "\"one\""
```

I get this error even though the file is valid TOML:

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    toml_dict = toml.load(f)
  File "/Volumes/HardDrive/test/python/toml/venv/lib/python3.5/site-packages/toml.py", line 105, in load
    return loads(f.read(), _dict)
  File "/Volumes/HardDrive/test/python/toml/venv/lib/python3.5/site-packages/toml.py", line 245, in loads
    raise TomlDecodeError("Unbalanced quotes")
toml.TomlDecodeError: Unbalanced quotes
```

This is running on master, commit 19b0f573fead0b239de20af98b86ac5ae265a74a.

**Comment by guyskk** [comment]
You need 2 backslash like this `test = "\\"one\\""`, the escape is misleading sometimes.

But it may be a bug when dealing with escape, no exception but unexpected result:

```python
import json
import toml

text1 = '{"test": "\\"one\\""}'
text2 = 'test = "\\"one\\""'

print(json.loads(text1))  # output: {'test': '"one"'}
print(toml.loads(text2))  # output: {'test': 'n'}
```

**Comment by jpotterm** [comment]
You only need two slashes in a string literal, not when reading from a file (which is my use case). The TOML spec says `\"` is the escape sequence for a string literal and `\\` is the escape sequence for a backslash. So if I put `test = "\"one\""` in a TOML file it would be parsed as having the value `"one"`. If I put `test = "\\"one\\""` then the backslashes are no longer escaping the quotes but themselves so that should be a syntax error. You can try it here: http://toml-online-parser.ovonick.com/

**Comment by uiri** [comment]
Thank you for the bug report! This has been fixed and a test added to the test suite.
