### ISSUE TITLE
ERROR with "Multi-line basic strings are surrounded by three quotation marks" 

### ISSUE THREAD

**Issue by KMiNT21** [uiri/toml#113]
https://github.com/toml-lang/toml#user-content-string

This lib doesn't work with strings are surrounded by three quotation mark as it can be by **"Tom's Obvious, Minimal Language" specification.** 

Example:

```
some_var = """
sdfsd fds dsfsdfsd sdfds 
sdfsdf dsfdsfsds dsfsdf
SDfsdfdsfsdf"""
```

"File "C:\Python\Python35\lib\site-packages\toml.py", line 463, in _load_value
    raise TomlDecodeError("Stuff after closed string. WTF?")
toml.TomlDecodeError: Stuff after closed string. WTF?"

**Comment by jmholla** [comment]
Your example doesn't seem to reproduce. Does the bug require a nested structure?

```
import toml

toml_str = '''\
some_var = """
sdfsd fds dsfsdfsd sdfds
sdfsdf dsfdsfsds dsfsdf
SDfsdfdsfsdf"""'''

print(toml.loads(toml_str))
```

**Comment by KMiNT21** [comment]
I have tried to load data from many "config.toml" (different GOHUGO templates configs):

`toml.load(filename)`

And found this problem with configs where these multi-strings was found. 
Changing to simple "string" fix this problem.

**Comment by nagisa** [comment]
Something like

```python
toml.loads('''foo = """bar "baz" qux"""''')
```

certainly reproduces.

**Comment by uiri** [comment]
@nagisa that looks like it might be a separate bug related to having single quote strings inside triple quote strings.

@KMiNT21 Hi Mykhail, I am having trouble reproducing this in a *nix environment. Maybe this is a Windows issue? Do you have an *nix (i.e. Linux, Mac, BSD) environment you can test the buggy toml files in?
