### ISSUE TITLE
Error when parsing table of arrays of tables of arrays of tables of tables where the lowest array has multiple entries

### ISSUE THREAD

**Issue by jmholla** [uiri/toml#115]
Here's an example of such a toml file:

```
[[a]]
    [[a.b]]
        [a.b.c]
            d = "val0"
    [[a.b]]
        [a.b.c]
            d = "val1"
```

The library has no problem producing the toml output from a python object constructed like so, but on attempting to parse it, it errors with "An implicitly defined table can't be an array". That does not seem to be the case in this file.

Removing one layer of table/array allows it to be read.

To be fair, the TOML to JSON tool I usually use to validate my TOML doesn't work correctly with this eiither: https://toml-to-json.matiaskorhonen.fi/, but I can't find anything in the spec that should limit this use case.

Here's that same toml input being dumped from a python object and then loaded.

```
import toml

toml_dict = { # TABLE
    "a": [ # ARRAY
        { # TABLE
            "b": [ # ARRAY
                { # TABLE
                    "c": {"d": "val0"}  # TABLE
                },
                { # TABLE
                    "c": {"d": "val1"}  # TABLE
                }
            ]
        }
    ]
}

toml.loads(toml.dumps(toml_dict))
```

**Comment by uiri** [comment]
Thank you for the bug report! I've fixed this and also added a regression test to the test suite.
