### ISSUE TITLE
Trailing new lines are stripped or mangled

### ISSUE THREAD

**Issue by adiroiban** [uiri/toml#116]
test code 

```
import toml

content = r"""
[test]

multi_line = "some lines\n\n"

"""

config = toml.loads(content)

print repr(config['test']['multi_line'])

```
Actual result: `u'some lines\n\\n'`
Expected result: `u'some lines\n\n'`

See the extra `\`

-------------

I get wrong errors if I am using values like

```

multi_line = "some lines\r\n"
multi_line = "some lines\r\n\r\n"

```

-----------

I have also tried this code

```
import toml

content = (
    '[test]\n'
    'multi_line = """some lines\n'
    '\n'
    '\n'
    '\n'
    '"""'
    )

config = toml.loads(content)

print repr(config['test']['multi_line'])
```

Actual result: `u'some lines\n'`
Expected result: `u'some lines\n\n\n\n'`

**Comment by uiri** [comment]
Is this bug still present in the latest development version?

**Comment by adiroiban** [comment]
nope. It looks good. thanks!

Is there a testing suite for the python toml?

**Comment by uiri** [comment]
The `CONTRIBUTING` file contains information about testing.

I use [my own fork of BurntSushi's test suite](http://github.com/uiri/toml-test) in addition to some other scripting.
