### ISSUE TITLE
Fails to serialize dictionaries that have numerical keys

### ISSUE THREAD

**Issue by jakory** [uiri/toml#117]
The toml library fails to serialize dictionaries that have numerical keys. 

**Expected behavior:** Numerical keys in the dictionary to serialize will be converted to strings when `toml.dumps` or `toml.dump` is called. (Like the behavior of the equivalent json functions `json.dumps` and `json.dump`).

**Actual behavior:** `toml.dumps` and `toml.dump` both return a `TypeError`.

**Example** (toml version 0.9.2, python 2.7.6):
```
import toml
d = {1: "stuff"}
toml.dumps(d)
```

**Expected output:**
```
>>> import toml
>>> toml.dumps(d)
'{"1": "stuff"}'
```

**Actual Output:**
```
>>> import toml
>>> d = {1: "stuff"}
>>> toml.dumps(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jakory/.local/lib/python2.7/site-packages/toml.py", line 597, in dumps
    addtoretval, sections = _dump_sections(o, "")
  File "/home/jakory/.local/lib/python2.7/site-packages/toml.py", line 619, in _dump_sections
    if not re.match(r'^[A-Za-z0-9_-]+$', section):
  File "/usr/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```

**Comment by uiri** [comment]
Hi, thank you for your bug report! I did not realize that `json.dump` and `json.dumps` handle non-string keys in dictionaries. This has now been fixed.

**Comment by jakul** [comment]
@uiri Are you aware that on Python 2 this bug fix converts an input `unicode` string into a `str` string for output? This is quite a serious change in behaviour! You may want to use `six.text_type` instead of `str`

**Comment by uiri** [comment]
Whoops, you're right. I need to use `unicode` instead.

There is a bit of hacky code at the top of the module which makes that work on both python 2 and python 3.
