### ISSUE TITLE
Whitespace handling in triple-quoted strings is broken

### ISSUE THREAD

**Issue by nagisa** [uiri/toml#119]
```
toml.loads('''foo = """
I expect newlines to be preserved?

Newlines please?
"""''')
```

returns

```
{ 'foo': 'I expect newlines to be preserved?\nNewlines please?\n' }
```

Where I'd expect a

```
{ 'foo': 'I expect newlines to be preserved?\n\nNewlines please?\n' }
```

**Comment by uiri** [comment]
Hi,

Are you running the latest master? It looks like it is fixed there although it may be present in the latest pip release. This may be a dup of #80 or #68.

**Comment by nagisa** [comment]
Not master. pip.

On Sep 1, 2017 7:54 AM, "Will Pearson" <notifications@github.com> wrote:

Hi,

Are you running the latest master? It looks like it is fixed there although
it may be present in the latest pip release. This may be a dup of #80
<https://github.com/uiri/toml/issues/80> or #68
<https://github.com/uiri/toml/issues/68>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/uiri/toml/issues/119#issuecomment-326487073>, or mute
the thread

**Comment by uiri** [comment]
Closing as dup of #90
