### ISSUE TITLE
Empty string in a list breaks parser

### ISSUE THREAD

**Issue by mikebentley15** [uiri/toml#133]
This is with version 0.9.3

Here is a minimal example that breaks the parser:

```python
import toml
toml.loads("hello = ['',]")
```

This results in the output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mbentley/anaconda3/lib/python3.6/site-packages/toml.py", line 373, in loads
    multibackslash)
  File "/home/mbentley/anaconda3/lib/python3.6/site-packages/toml.py", line 478, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "/home/mbentley/anaconda3/lib/python3.6/site-packages/toml.py", line 637, in _load_value
    return (_load_array(v, _dict), "array")
  File "/home/mbentley/anaconda3/lib/python3.6/site-packages/toml.py", line 714, in _load_array
    while ab[-1] != ab[0] or (ab[0] == ab[1] == ab[2] and
IndexError: string index out of range
```

It's not only because of the trailing comma.  Here is another example that causes the same problem

```python
import toml
toml.loads("hello = ['', 'world']")
```

But you may notice that it works if the empty string is at the end of the list

```python
import toml
toml.loads("hello = ['world', '']")
```

For my application, I need to be able to specify an empty string in a list.  For now, I can put it at the end.  This used to work in older versions of the toml package.  Specifically, I have confirmed it working in version 0.9.1.

**Comment by uiri** [comment]
Hi Mike,

Thank you for reporting this issue. I added a length check which appears to have fixed the problem.

**Comment by mikebentley15** [comment]
Thank you uiri.  As an aside, it may be a good idea to add an example like this to your toml-test repository for regression.
