### ISSUE TITLE
Roadmap for 1.0 release?

### ISSUE THREAD

**Issue by waisbrot** [uiri/toml#134]
The library seems quite usable. I think 1.0 releases are a good way to communicate that things are stable and working.

I realize the TOML standard itself is not at 1.0 (toml-lang/toml#482) but as the issue there says, 0.4 is de facto 1.0 because Tom doesn't want to break compatibility.

Anyway, given the standard that we have, is there anything you feel is lacking for a 1.0 release?

**Comment by uiri** [comment]
I am about to break everything to address 4-5 issues which are currently open.

Take a look at the `user-custom` branch.

**Comment by waisbrot** [comment]
Excellent! Thanks for the reply!
