### ISSUE TITLE
Numpy numeric types and arrays should be recognised

### ISSUE THREAD

**Issue by samvasko** [uiri/toml#138]
numpy is commonly used and should be supported as an input o the dumps function.

```
import toml
import numpy as np

test_ar = np.array([1, .3], dtype=np.float64)
toml.dumps(test_ar)
```

Currently I am getting:

`TypeError: Required argument 'shape' (pos 1) not found`

**Comment by uiri** [comment]
I agree that NumPy numeric types and arrays should be recognized.

Does NumPy have a dictionary/key-value store type? If not, I think you should need to wrap it in a regular dictionary (or subtype).

Also, it should be possible for `loads` to use NumPy types with a custom `TomlEncoder`.

**Comment by uiri** [comment]
FYI: All iterables should be recognized as of the fix for #168

**Comment by uiri** [comment]
The dumps function is supposed to take a dictionary of keys and values.

It looks like if you set a NumPy array of floats as one of the values, it gets dumped as strings. I suppose they should be dumped as floats instead.

```
>>> import toml
>>> import numpy as np
>>> d = {'a': np.array([1, .3], dtype=np.float64) }
>>> toml.dumps(d)
u'a = ["1.0", "0.3",]\n'
```

**Comment by uiri** [comment]
Closing as I've added a `TomlNumpyEncoder` to take care of the float types.

Feel free to send a pull request for any other types that may be missing.

**Comment by filippo82** [comment]
Hi @uiri, when are you planning to upload the latest version (with **TomlNumpyEncoder**) on PyPi?

**Comment by uiri** [comment]
Hi Filippo, there are on-going PRs relating to a comment preserving decoder/encoder combo. Once that work is wrapped up, I will prep another release.
