### ISSUE TITLE
toml.load raises inhomogeneous array warning

### ISSUE THREAD

**Issue by dirkphilip** [uiri/toml#149]
Hey there, 

I'm trying to read a file which contains the following:

[[source]]
location = [2691118.9072999307, 4586901.1271202704, 3484464.113849102]

This raises the following error:
toml.TomlDecodeError: Not a homogeneous array.
If I slightly change the amount of digits in the numbers toml.load manages 
to read the entry just fine. But under certain cases I get this error message.

Any idea what could be going on here? Is this not a valid format?

Thanks a lot!

**Comment by dirkphilip** [comment]
btw I am running toml 0.9.4 on python 3.6

**Comment by uiri** [comment]
Thank you for your bug report! It turns out that sometimes your floats were the exact right length to be a datetime.

I have fixed this bug in the development branch and the fix will be included in the next release.

**Comment by dirkphilip** [comment]
Hey, thanks a lot!
