### ISSUE TITLE
dumping should fail for unsupported data types

### ISSUE THREAD

**Issue by silentquasar** [uiri/toml#151]
At present, if an object of unsupported data type (e.g. tuple) is provided to `_dump_value`, it is simply returned as-is and is written to the toml string or file in its string representation (but without quotes). This gives the user the impression that there is nothing wrong with the supplied data. However, not only is the created toml string/file invalid, but toml.load[s] cannot read in the object. 

Propose raising error in `_dump_value` if `type(v) not in dump_funcs`.

Example current (bad) behavior:
```
>>> config_start = {'the_tuple': (3, 4, 5)}
>>> toml_conf = toml.dumps(config_start)
>>> config_end = toml.loads(toml_conf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/shared/anaconda3/lib/python3.6/site-packages/toml.py", line 373, in loads
    multibackslash)
  File "/shared/anaconda3/lib/python3.6/site-packages/toml.py", line 478, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "/shared/anaconda3/lib/python3.6/site-packages/toml.py", line 664, in _load_value
    v = int(v)
ValueError: invalid literal for int() with base 10: '(3, 4, 5)'
```

Expected behavior:
```
>>> config_start = {'the_tuple': (3, 4, 5)}
>>> toml_conf = toml.dumps(config_start)
Traceback blah...
    blah...
    blah...
TypeError: `tuple` type not supported in TOML.
```

**Comment by uiri** [comment]
Is this about tuples specifically? Or about arbitrary Python objects in general?

A tuple should *probably* just be turned into a list and serialized properly.

More generally, I don't see anything wrong with the current behaviour except that quotes should most likely be applied.

**Comment by diefans** [comment]
@uiri The problem is, that you cannot load a "successfully" dumped toml file, which should be possible. 

Leaving data validation/rejection to the application, implies to read and implement parts of the toml specification, which I would expect this library is created for...
