### ISSUE TITLE
toml.load doesn't support python3's pathlib.Path objects 

### ISSUE THREAD

**Issue by QJKX** [uiri/toml#159]
Hi
`toml.load` doesn't work with python3's `pathlib.Path` objects.

Perhaps the pythonic way of fixing this would be to remove the `isinstance` expressions and to use duck typing instead.

**Comment by uiri** [comment]
Thank you for your bug report!

I don't think that ducktyping quite works for 3.4 and 3.5, unfortunately, and I am maintaining backwards compatibility with python 2 for now.
