### ISSUE TITLE
Encoder will emit invalid Nones

### ISSUE THREAD

**Issue by alethiophile** [uiri/toml#160]
```
>>> toml.dumps({'title': [ None ]})
'title = [ None,]\n'
```
This is not valid TOML, since TOML does not allow barewords (and indeed doesn't have any concept of null/none anyway). Sure enough,
```
>>> toml.loads(toml.dumps({'title': [ None ]}))
Traceback (most recent call last):
  File "/home/tom/dev/toml/toml/decoder.py", line 395, in loads
    multibackslash)
  File "/home/tom/dev/toml/toml/decoder.py", line 587, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/tom/dev/toml/toml/decoder.py", line 661, in load_value
    return (self.load_array(v), "array")
  File "/home/tom/dev/toml/toml/decoder.py", line 767, in load_array
    nval, ntype = self.load_value(a[i])
  File "/home/tom/dev/toml/toml/decoder.py", line 686, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit
```
It's invalid markup, so it's correct to error out, though the error message is a bit obtuse. I'd guess the correct answer is just to explicitly fail on encoding array-of-None.

**Comment by uiri** [comment]
Hi,

Thank you for your bug report. I agree that the error message could be a bit better but that would require the parser to classify the bad value according to which type it most likely thinks it is. I would rather not special case null/`None` if I can avoid it.

**Comment by alethiophile** [comment]
I was thinking more along the lines of just an "invalid bareword" error, rather than jumping into thinking it was a float only because it contained the letter 'e'.

But the bigger point is just that the parser shouldn't emit that. I guess just erroring on array-of-none is probably best? (The parser will also emit a mixed array, which is also invalid TOML.)
