### ISSUE TITLE
Infinite loop in parsing simple string

### ISSUE THREAD

**Issue by jnwatson** [uiri/toml#161]
The following code loops forever:
```
import toml
s = '''[[ test ]]\n[ "foo", ]'''
toml.loads(s)
```

So much for my first toml file. :(

**Comment by uiri** [comment]
Thank you for your bug report! This should really generate an error rather than loop since the example you provided is not valid toml.

What was the result that were you expecting?

**Comment by jnwatson** [comment]
I was expecting an error.

**Comment by ckauhaus** [comment]
Stumbled on the same bug. Getting into an endless loop is absolutely not an option. The parser should generate an exception.
