### ISSUE TITLE
dotted keys aren't supported

### ISSUE THREAD

**Issue by radix** [uiri/toml#163]
The [TOML spec](https://github.com/toml-lang/toml#keys) specifies that the following syntax is valid:

`a.b.c = "hello"`

to give you a structure like

`{'a': {'b': {'c': 'hello'}}}`

the `toml` python library just raises an exception when parsing a key, saying that a `.` is unexpected and that the key should be quoted.

**Comment by pradyunsg** [comment]
That's because this library is TOML 0.4.0 compliant -- dotted keys are a not-yet released feature of TOML {expect that to happen in TOML v1.0).
