### ISSUE TITLE
Upload wheel to PyPI

### ISSUE THREAD

**Issue by EdJoJob** [uiri/toml#164]
There are tools that will only download wheels from PyPI.  I want to use this library from those tools.  As this is a python only library with no compiled extensions this should be as simple as building and uploading a `bdist` alongside the `sdist`

**Comment by jdufresne** [comment]
Yes, please.

Advantages of wheels

- Faster installation.
- Avoids arbitrary code execution for installation. (`Avoids setup.py`)
- Allows better caching for testing and continuous integration.
- Creates `.pyc` files as part of installation to ensure they match the Python interpreter used.
- More consistent installs across platforms and machines.

To upload wheels to PyPI, when you would normally run `python setup.py sdist upload`, run instead `python setup.py sdist bdist_wheel upload`.

Or if you use twine, see https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives

```bash
$ python3 setup.py sdist bdist_wheel
$ twine upload dist/*
```

For more information on wheels, see:

- https://pythonwheels.com/
- https://wheel.readthedocs.io/en/stable/

**Comment by uiri** [comment]
Closed by latest 0.9.X release with backported bugfixes
