### ISSUE TITLE
Single URL entry: This float doesn't have a leading digit

### ISSUE THREAD

**Issue by dirkjonker** [uiri/toml#166]
Sample file:
```
[foo]
url = https://google.com
```

This will raise a very strange error:
```
>>> toml.load('my.toml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dirkjonker/projects/dcos-python/venv/lib/python3.6/site-packages/toml.py", line 88, in load
    return loads(ffile.read(), _dict)
  File "/Users/dirkjonker/projects/dcos-python/venv/lib/python3.6/site-packages/toml.py", line 373, in loads
    multibackslash)
  File "/Users/dirkjonker/projects/dcos-python/venv/lib/python3.6/site-packages/toml.py", line 478, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "/Users/dirkjonker/projects/dcos-python/venv/lib/python3.6/site-packages/toml.py", line 660, in _load_value
    raise TomlDecodeError("This float doesn't have a leading digit")
toml.TomlDecodeError: This float doesn't have a leading digit
```

**Comment by dirkjonker** [comment]
Might be intended behavior... I'll check the specs

**Comment by dirkjonker** [comment]
It seems that under my particular circumstance, `toml.dumps` writes the url without quotes. I cannot yet reproduce it but it is with Python 2.7 and a dict like
```python
{'foo' {'url': u'https://some.website.with.subdomains.com'}}
```
Note the url being `unicode` while the keys are `str`

**Comment by uiri** [comment]
Hi Dirk,

Thank you for your bug report!

Is this a dictionary that you are trying to roundtrip through `toml.dumps` and then `toml.load` ? Or does `toml.load` generate a dictionary with inconsistencies between `unicode` and `str` in keys and values?

**Comment by dirkjonker** [comment]
The problem was that the toml was written (using `toml.dumps`) without quotes around the url, but I have been unsuccessful in reproducing it.

**Comment by uiri** [comment]
Is it OK if I close this issue since you can't reproduce it? Feel free to re-open it at any time if that changes.

**Comment by dirkjonker** [comment]
No problem!
