### ISSUE TITLE
Cannot load a dumped `dict` containing `set`

### ISSUE THREAD

**Issue by ayharano** [uiri/toml#168]
Hello there.

I looked the issues but I didn't find one that exactly matches this. If there is, I apologize for opening a duplicate.

The following code uses the most recent code in this repositories' master with python 3.6.5:

```python
>>> import toml
>>> dict_with_set = {'filled_set': set({1, 2}), 'empty_set': set({})}
>>> toml.dumps(dict_with_set)
'filled_set = {1, 2}\nempty_set = set()\n'
>>> toml.loads(toml.dumps(dict_with_set))
Traceback (most recent call last):
  File "/Users/user/dev/tools/toml/toml/decoder.py", line 545, in load_inline_object
    _, value = candidate_group.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/dev/tools/toml/toml/decoder.py", line 419, in loads
    multibackslash)
  File "/Users/user/dev/tools/toml/toml/decoder.py", line 611, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/Users/user/dev/tools/toml/toml/decoder.py", line 688, in load_value
    self.load_inline_object(v, inline_object)
  File "/Users/user/dev/tools/toml/toml/decoder.py", line 547, in load_inline_object
    raise ValueError("Invalid inline table encountered")
ValueError: Invalid inline table encountered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/dev/tools/toml/toml/decoder.py", line 421, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid inline table encountered (line 1 column 1 char 0)
```

I don't know if this is considered in `loads`, but maybe it relates to the fact that `set`'s `__repr__` and `__str__` use braces when outputing:

```python
>>> s = set({1, 2})
>>> repr(s)
'{1, 2}'
>>> str(s)
'{1, 2}'
```

**Comment by uiri** [comment]
Hi ayharano,

Thank you for bringing this to my attention. It looks like the output of `toml.dumps` is not valid toml.

Which toml data type are you expecting the sets to be output as? My closest guess would be an array.

I'm afraid toml itself does not have sets so you will need to cast the values which should be sets from toml arrays (which are represented by the library as python lists).

**Comment by ayharano** [comment]
Sorry for not providing feedback before. The adopted solution was similar to what I did in my procedure to convert existing data into valid toml's loads(dumps(data)) approach.

Thank you very much!
