### ISSUE TITLE
Would anyone use this over PyTOML?

### ISSUE THREAD

**Issue by thechief389** [uiri/toml#174]
There's is a similar TOML parser named [PyTOML](https://github.com/avakar/pytoml). Will it be worth discontinuing this project and move on to the latter?

**Comment by eksortso** [comment]
Don't expect PyTOML to add any new features. Unless the lead developer had a change of heart, that is. [He abandoned TOML two years ago.](https://github.com/avakar/pytoml/issues/15#issuecomment-217739462)

**Comment by uiri** [comment]
Hi @thechief389,

This project is about as old as the TOML spec itself. If you want to know why another, similar parse exists, you would have to ask the maintainer of that project. I think it is healthy for any spec to have multiple implementations, even in the same programming language.

I do not currently have any plans to abandon this project so long as downstream users keep reporting bugs and requesting features. My contributions to this project are made strictly on my own time. While I wish I had more free time to devote to it, that does not seem likely in the foreseeable future.

Seeing as this is neither a bug nor a feature request, I am closing this as WONTFIX.

If you have any feature requests or bugs to report, please open a new issue.

Thanks,
-Will
