### ISSUE TITLE
No tests in pypi source

### ISSUE THREAD

**Issue by dvzrv** [uiri/toml#192]
Hi!

I'm currently trying to package toml for Arch Linux [community].
However, the tests are not in the source tarball on pypi (and I would like to run them). I can't take the github source tarball of 0.9.4 either (because there's none).

Can you include the tests in the next version and tag 0.9.4 in this repository, so that a tarball is generated here as well (I could use that meanwhile)?
Thanks!

**Comment by uiri** [comment]
Thank you for pointing out the missing tag. Oops. I have pushed the tag for 0.9.4

I can include the tests, but, out of curiosity, why do you want them packaging?

The TOML compliance portion of the test suite is maintained in a separate repository which provides a language agnostic test suite. The API tests are a more recent addition.

**Comment by dvzrv** [comment]
np ;-)

We generally run the tests for python packages, as (ideally) this way we can ensure, that the package actually builds with the rest of the dependencies and python version from the repositories.
It's not about having the tests in the wheel package, but in the source package (as that's what we build from)!

**Comment by dvzrv** [comment]
Hm, for running the tests, it still requires the `test.toml` though
