### ISSUE TITLE
Package documentation should be more clear about supported TOML specification

### ISSUE THREAD

**Issue by vlotorev** [uiri/toml#203]
When rendered https://github.com/uiri/toml/blob/master/README.rst doesn't specify explicitly what TOML version it supports.

Also section link for "The current TOML specification" is contruintuitive at all as it notifies the user about "what current TOML specifications exists" while user expects information about the "what TOML this Python package supports".

**Comment by FichteFoll** [comment]
+1. Was expecting support for date parsing, but apparently this was only [added in 0.5](https://github.com/toml-lang/toml/blob/master/CHANGELOG.md#050--2018-07-11) and seemingly no Python parser supports that currently. tomlkit claims to do so, however, so I'll check that out for now.

**Comment by uiri** [comment]
Hi Vitaliy,

Thank you for reporting this.

"The current TOML specification" refers to the current specification supported by the library. I agree that the language there could be more clear. I have also noticed that I did not update the `_spec_` variable in the source from 0.4.0 to 0.5.0.

The library does support local date and time parsing as of version 0.9.6.
