### ISSUE TITLE
Parsing fails on inline array of tables containing a nested table

### ISSUE THREAD

**Issue by jorisvr** [uiri/toml#205]
Input:

     toml.loads("a = [ { b = {} } ]")

Result: `toml.decoder.TomlDecodeError: Invalid inline table value encountered (line 1 column 1 char 0)`

Expected result: `{ "a": [ { "b": {} } ] }`

**Comment by uiri** [comment]
Thank you for the bug report! This is definitely a bug :)

**Comment by abatea** [comment]
I'm still seeing this bug. In the most recent master, I see the edits that attempt to fix the issue, but I still get the same error with the same minimal example.
