### ISSUE TITLE
Parser accepts invalid bare key containing =

### ISSUE THREAD

**Issue by jorisvr** [uiri/toml#208]
For example:

    toml.loads("a==1")

Result: `{'a=': 1}`
Expected: decoding error

Similarly, this is also accepted:

    toml.loads("a=b=1")

Result: `{'a=b': 1}`

**Comment by uiri** [comment]
Thank you for reporting this.

In the past, the TOML spec was somewhat ambiguous on this point such that it seemed to imply *the last* equals sign was to separate a key from its value. With the introduction of quoted keys, the language around valid characters for keys was tightened up. Given that the current behaviour supports all keys that are valid under the 0.4.0/0.5.0 specs, and that changing this to a decoding error may break TOML documents which worked under older versions of this library, I am a bit hesitant to make parsing more strict.

**Comment by jorisvr** [comment]
Ok thanks for your explanation.

I personally think it is unfortunate that this introduces an implementation-defined _dialect_ around the edges of the TOML specification. But I understand your concern regarding backwards-compatibility - it is a valid point. Dealing with multiple versions of standards is never easy.
