### ISSUE TITLE
Add support for specifiying dict types

### ISSUE THREAD

**Issue by inklesspen** [uiri/toml#21]
ConfigParser takes a `dict_type` argument (and, in python2.7, defaults to `collections.OrderedDict`). It would be useful to have the option of specifying an ordered dict when loading TOML files.

**Comment by uiri** [comment]
I'm considering this closed by 3869c1d
Please re-open if support is considered incomplete.

**Comment by inklesspen** [comment]
@uiri Thanks, but I'm worried it's only been addressed at the top level; there's code like `currentlevel[group] = {}` that still constructs dicts with the `{}` literal.

**Comment by uiri** [comment]
I think that I got all the places where I used the `{}` literal. Let me know if I missed a spot!
