### ISSUE TITLE
Booleans should accept "yes"/"no" as well as "true"/"false"

### ISSUE THREAD

**Issue by FrankDMartinez** [uiri/toml#212]
One thing which helps people who have to make configuration files without programming experience is to make things as straightforward and simple as practical. Allowing "yes" in addition of "true" and "no" in addition of "false" for booleans will help.

Thanks in advance.

**Comment by uiri** [comment]
Hi Frank,

This library implements v0.5.0 of the spec described in [toml-lang/toml](https://github.com/toml-lang/toml).

Perhaps you meant to make this feature request there so that it may be added to the next version of the spec and then implemented in this library once that version is released?

**Comment by FrankDMartinez** [comment]
No, in my experience getting an extension added to one implementation of a specification/standard is far easier than getting the actual specification/standard modified. And doing so makes sense; for example, the ISO C++ committee will not consider any proposal to add new features to the C++ standard unless at least one compiler implements that feature because how do you standardize on something literally nobody uses?

**Comment by gaborbernat** [comment]
I personally would advise against stirring away from the standard, it will just lead into toml files being parser bound to a specific implementation. The whole point of toml is that it's language and parser agnostic.

**Comment by uiri** [comment]
Frank,

If you want to submit a PR which simplifies a custom encoder/decoder that implements this feature, I will take a look at it. This TOML implementation is designed to make it easy for end users to write their own extensions without cluttering up the core with non-standard features.

If you want this feature added to the core library, I strongly recommend you open up an issue in the repository for the standard to which I have already linked.
