### ISSUE TITLE
Calling load(list_of_files, _dict=OrderedDict) does not return an OrderedDict

### ISSUE THREAD

**Issue by erkyrath** [uiri/toml#234]
The _dict argument is ignored for the top-level object.

**Comment by LexiconCode** [comment]
Thank you I was going to look into this as well.

**Comment by uiri** [comment]
Thank you for reporting this issue!

It looks like I forgot to pass `_dict` to the constructor for `TomlDecoder` in `load`. This has been fixed in the latest master branch.
