### ISSUE TITLE
Type Hinting for public APIs

### ISSUE THREAD

**Issue by xNinjaKittyx** [uiri/toml#251]
This is definitely a low priority, but it would helpful to have type hinting for the public APIs available.

**Comment by uiri** [comment]
Are type hints backwards compatible with Python 2.7 and 3.4?
Unfortunately, I don't think this library will have them for quite a while if not.

**Comment by xNinjaKittyx** [comment]
It's possible... (using comments) but might not be worth it.
https://mypy.readthedocs.io/en/latest/python2.html

Feel free to close if not applicable.

**Comment by uiri** [comment]
Thank you for raising this issue but I am going to punt on type hinting until I am comfortable moving the library to support only Python 3.5+
