### ISSUE TITLE
Toml grammar does not require whitspace in key=value

### ISSUE THREAD

**Issue by salmangano** [uiri/toml#257]
Here is the toml grammar:

keyval = key keyval-sep val
keyval-sep = ws %x3D ws 
ws = *wschar     NOTE OPTIONALITY OF wschar

**Comment by eksortso** [comment]
Is there a reason you opened this as an issue? It works as originally planned after all.

**Comment by salmangano** [comment]
$ cat test.toml
time=10:00:00

$ cat test2.toml
time = 10:00:00

$ python test.py test.toml
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    toml.load("./test.toml")
  File "/usr/lib/python2.7/site-packages/toml/decoder.py", line 112, in load
    return loads(ffile.read(), _dict, decoder)
  File "/usr/lib/python2.7/site-packages/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid date or number (line 1 column 1 char 0)

$ python test.py test2.toml
$



[toml-257.zip](https://github.com/uiri/toml/files/3707424/toml-257.zip)

**Comment by eksortso** [comment]
Good catch. It's a bug in Python 3.7.1 and toml library v0.10.0.

```python
>>> import toml

>>> s1 = "time = 10:00:00"

>>> toml.loads(s1)
{'time': datetime.time(10, 0)}


>>> s2 = "time=10:00:00"

>>> toml.loads(s2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\dave.ostroske\appdata\local\programs\python\python37\lib\site-packages\toml\decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid date or number (line 1 column 1 char 0)

Invalid date or number (line 1 column 1 char 0)
```

It probably isn't a problem with the spacing so much as it's a problem with how times are parsed. I tried the same thing with string values and had no problems.

```python
>>> t1 = 'day = "Thursday"'

>>> toml.loads(t1)
{'day': 'Thursday'}


>>> t2 = 'day="Thursday"'

>>> toml.loads(t2)
{'day': 'Thursday'}
```

**Comment by salmangano** [comment]
Thanks. FWIW we use Python 2.7.x  not 3.x.x

**Comment by salmangano** [comment]
The following change will fix this issue:
725             if _load_date(pair[-1]) is not None:
726                 break
**727             if TIME_RE.match(pair[-1]):
728                 break**

**Comment by salmangano** [comment]
This issue is resolved by https://github.com/uiri/toml/pull/266

**Comment by efiring** [comment]
@uiri A gentle reminder: please close this issue since it has been resolved.
