### ISSUE TITLE
Unhelpful, unprofessional error message.

### ISSUE THREAD

**Issue by thisfred** [uiri/toml#259]
https://github.com/uiri/toml/blob/master/toml/decoder.py#L817

'stuff' is imprecise and unhelpful, 'wtf' does not communicate anything helpful to the user, and is unprofessional.

More helpful would be to show the leftover value(s), possibly truncated if they are very long.

**Comment by uiri** [comment]
This error message has been present basically unchanged since 2013.  
Teenage me was not very good at error messages.

**Comment by thisfred** [comment]
Thank you for the quick turnaround! We were all young and not good at many things once. ;)
