### ISSUE TITLE
0.10.1 on PyPI

### ISSUE THREAD

**Issue by filippo82** [uiri/toml#267]
Good morning,

are you planning to update toml on PyPI too soon? It is now still at version 0.10.0.

Thank you,
-Filippo

**Comment by mileslucas** [comment]
Bump,

I am waiting to do a PyPI release on my project because I can't have git dependencies, but I need 0.10.1 in my project.

**Comment by filippo82** [comment]
Hello,

are there any updates on this?

Best wishes.

**Comment by VSHUMILIN97** [comment]
Greetings,
Just a friendly comment to bump activity on this issue. Our team is desperate for the "preserve comments" feature and w/ poetry we can't really afford to build from source.

Best wishes and be healthy :)

**Comment by mileslucas** [comment]
Any update on this? If not I'm going to just copy and paste the code from 10.1 into my repo. No maintainer response on this simple issue for over 3 months (almost 4!) is ridiculous.

**Comment by filippo82** [comment]
They are not paid to do this so your comment is unnecessary. This repo has an MIT license so this gives you a lot of freedom.

**Comment by hugovk** [comment]
If being paid would help, there's a modest amount up for grabs via Tidelift:

https://tidelift.com/lifter/search/pypi/toml

**Comment by pradyunsg** [comment]
@uiri If there's a lack of availability of maintainer time on this project, I am happy to share the maintenance burden on the project.

I'm fairly... involved in both [TOML](https://github.com/toml-lang/toml/graphs/contributors?from=2017-10-05&to=2020-04-04&type=c) and [Python](https://github.com/pypa/pip/graphs/contributors) ecosystems, so I'd be more than happy to help. :)

**Comment by asherf** [comment]
@uiri bump/ping

**Comment by asherf** [comment]
yay! looks like a new release is up on pypy
https://pypi.org/project/toml/0.10.1/
Thanks @uiri

**Comment by filippo82** [comment]
woot woot!

**Comment by pradyunsg** [comment]
Hmm... there hasn't been much activity since 0.10.1. :(

@uiri My offer from https://github.com/uiri/toml/issues/267#issuecomment-609112291 still stands.

**Comment by CAM-Gerlach** [comment]
@uiri It is rather sad and worrying that what seems to be the most popular TOML library currently has been entirely unmaintained and does not support the current, stable 1.0 version of the spec, despite a large amount of community interest in contributing and moving things forward.

There seem to be several options, from most to least preferred:

Ideally, this repository could be moved to a Github org with the appropriate contributors added, which would reduce avoid a single point of failure with it depending on a user's personal account; however, it would require the project adopt a new name on PyPI, and downstream users manually update their dependencies.

Collaborator access could be granted to one or more experienced contributors, and development continued here.

Finally, this repo could be archived and users pointed toward an active fork or replacement project.

All of these, however, are better for everyone involved than simply keeping the status quo, as eventually either users will have to fork the project, choose a new name on PyPI and rebuild the community anew, or abandon it altogether and have it die a slow, easily avoidable death.

Given @pradyunsg , an experienced, well-known, clearly deeply subject-matter-knowledgeable community member willing to take on the work has offered to step in to move things forward, it would certainly be ideal if maintainership (and more importantly, PyPI deploy access) could be shared with them. However, after a year of no response, and very little Github activity by the current maintainer, it might be time to consider a fork, unless the community prefers adopting an alternative toml parser (Tomli seems nice, but doesn't have widespread adoption yet, and I've ran into a number of edge-case bugs and subtle incompatibilities with tomlkit for use cases that don't need to preserve style).
