### ISSUE TITLE
Please update on pypi to latest code

### ISSUE THREAD

**Issue by efenfauzi** [uiri/toml#292]
I found error exception with bad language '**Stuff after closed string. WTF?**',I know this is old msg and related on pypi with current version 0.10.0. Please update on pypi with latest code for better use to common.

**Comment by Julian** [comment]
660dd2d57278e6f608bbaedcaaa4529ace557e41 also would also be really nice to have in a release -- the version pip currently vendors (which is 0.10 so latest released) raises these DeprecationWarnings.

**Comment by hugovk** [comment]
See also https://github.com/uiri/toml/issues/267

**Comment by asherf** [comment]
+1 for for this
Also the deprecation error that was fixed a while ago https://github.com/uiri/toml/commit/660dd2d57278e6f608bbaedcaaa4529ace557e41 
would love to get a new release.

**Comment by asherf** [comment]
yay! looks like a new release is up on pypi
https://pypi.org/project/toml/0.10.1/
Thanks @uiri

**Comment by filippo82** [comment]
woot woot!

**Comment by pradyunsg** [comment]
Awesome. In that case, this issue can be closed now. :)

**Comment by efenfauzi** [comment]
awesomee... thanks....
