### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by mraspberry** [uiri/toml#294]
Is this project still under active development? If you need more help or want someone to take over development I’m happy to assist in any way needed.

**Comment by uiri** [comment]
Hi!

I do see the notifications for new issues and pull requests but unfortunately I have been too busy to devote much time to looking into them lately.

**Comment by mraspberry** [comment]
No problem, like I said if you need additional help I'm happy to assist. I appreciate the awesome toml you've written. With pytoml now being deprecated and pointing it's user base to this library it'll get more attention i'm sure.

**Comment by filippo82** [comment]
Dear @uiri,

thanks again for your work and we understand you are busy. However, a few people (@mraspberry  above here and @pradyunsg in this issue #267 ) have already offer to help and it would be valuable for the entire community to bring them onboard.

Best.

**Comment by pradyunsg** [comment]
As I've said, I'm happy to pick up maintainance of this package.

**Comment by mraspberry** [comment]
Closing this since the project is still active.
