### ISSUE TITLE
Dicts from parsed datetime with a timezone cannot be deep-copied

### ISSUE THREAD

**Issue by jpsca** [uiri/toml#308]
The resulting dict from parsing a datetime with a timezone cannot be deep-copied using
the stdlib function `copy.deepcopy()`.

## Example

```python
import copy
import toml

o = toml.loads("dob = 1979-05-27T07:32:00-08:00")
copy.deepcopy(o)
```

## What happens now

```python
TypeError: __init__() missing 1 required positional argument: 'toml_offset'
```

## What should happen

The dict is copied and the timezone of the copy has the same offset but it is a different object.

**Comment by seperman** [comment]
I'm running into the same issue too.

**Comment by seperman** [comment]
I see you have a commit in your own fork @jpsca

**Comment by jpsca** [comment]
Yes, and I made a PR with the fix: https://github.com/uiri/toml/pull/309
