### ISSUE TITLE
Hangs when parsing "x=1_2"

### ISSUE THREAD

**Issue by hamstergene** [uiri/toml#31]
`toml-0.8.2` hangs on either of these lines:

    toml.loads("x=1_2")
    toml.loads("x=2015-01-01T12:30:30") # no 'Z' at the end
    toml.loads("x=2015-01-01_12:30:30Z")

**Comment by uiri** [comment]
I've managed to reproduce this issue in the current master.
For now I raise an Exception but the toml spec says that it should accept RFC 3339 dates so I need to be more flexible in the format strings I accept. For this reason, I am leaving this issue open for now.

**Comment by octycs** [comment]
Probably fixed this in #32.

**Comment by octycs** [comment]
I've just read why you tried to use underscores ([this](https://github.com/toml-lang/toml/issues/295) issue which is very likely to be implemented). Because they don't affect the number itself, I'd suppose to just remove them if the value is not in quotes and then check the data type.
