### ISSUE TITLE
Allow lists of file like objects in load

### ISSUE THREAD

**Issue by wonkodv** [uiri/toml#337]
The following is allowed:

  d = toml.load(io.StringIO("a=1"))
  d = toml.load(["a.toml", "b.toml"])

But not 

  d = toml.load([io.StringIO("a=1"), io.StringIO("b=2")])

The reason is this check:
https://github.com/uiri/toml/blob/3f637dba5f68db63d4b30967fedda51c82459471/toml/decoder.py#L148

It should be replace with a try-except FileNotFoundError because:

a) It would be more idiomatic (EAFP)
b) the current  is counterintuitive

**Comment by pradyunsg** [comment]
Please use a loop calling `toml.load` on each object instead. If you want, you can define a `load_many` function in your project, that loops over the inputs to provide the appropriate output.

```
def load_many(items):
     for item in items:
          yield toml.load(item)
