### ISSUE TITLE
Underline characters ignored in string values

### ISSUE THREAD

**Issue by wizeman** [uiri/toml#35]
Using the latest git commit, it seems that underline characters in string values are being ignored:

```python
>>> toml.loads('x="a_b"')
{'x': 'ab'}
```

I don't think that I'm missing some escape character, because if I start from a valid python string, then dump it into toml format, and then parse it back, the underline characters are still lost:

```python
>>> toml.loads(toml.dumps({'x': 'a_b'}))
{'x': 'ab'}
```

**Comment by uiri** [comment]
Thank you for the bug report. I believe that I have just fixed this.

Underscores are supposed to be stripped when they are in number values (integers, floats) but I put the stripping too early to be sure that the value is a number. I added a check to make sure that I only remove underscores in values which start with a digit (so not strings or arrays or things of that sort).

Feel free to reopen this if the issue persists.

**Comment by wizeman** [comment]
The fix seems to work. Thanks for such a quick fix!
