### ISSUE TITLE
Feature request: Open TOML file on AWS S3 bucket

### ISSUE THREAD

**Issue by gcaria** [uiri/toml#395]
It seems that toml files located on a AWS S3 bucket can't be read:
```python
import toml
toml.load('s3://path/to/toml')

FileNotFoundError: [Errno 2] No such file or directory: 's3://path/to/toml'
```
Could this be implemented?

**Comment by uiri** [comment]
You should use the AWS SDK for Python (see [documentation for S3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html) ) to download the TOML locally.

It doesn't look like the SDK provides access through a File-like object, so the best bet is probably to wrap the 'Body' returned by [.get()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Object.get) in a StringIO object or something like that.
