### ISSUE TITLE
toml.load(path) no directory found

### ISSUE THREAD

**Issue by stephexcel2004** [uiri/toml#406]
I have tried to use toml.load(path) where the path is a mounting directory in synapse (synfs:/.../../example.toml)

However, it returns FileNotFoundError(2, 'No such file or directory')

May I know whether synfs:/ path will be supported?

**Comment by pradyunsg** [comment]
It won't be supported, unless it is also supported by Python's open.

The load function expects a regular readable stream, so it might be possible to use an intermediary package to do the I/O with synfs -- that's research that you'll have to do yourself.
