### ISSUE TITLE
cannot round-trip key with odd characters

### ISSUE THREAD

**Issue by dholth** [uiri/toml#53]
Trying to write some toml.
```
[section]
":sys_platform==\"win32\"" = ["sdl2_lib"]
```

I had several problems. First, had to quote the key (fair enough), second, when quoted incorrectly the toml parser thought the == separated the key and value, third, it wanted to parse "sdl2_lib" as a number or possibly a date.

Please let me know if this is a bug with uiri/toml or if I'm just writing it wrong. Thanks.

**Comment by dholth** [comment]
This does not round-trip.

`toml.loads(toml.dumps({'foo=bar': ['sdl2_lib']}))`

**Comment by uiri** [comment]
If you incorrectly quote the key, the value which is getting parsed is garbage which results in the parser exhausting its options for determining what type of value it got. The last type of value which gets parsed is a date or number, hence the error message which you saw.

Which version of toml are you using? I get:

>>> import toml
>>> a = {'foo=bar': ['sdl2_lib']}
>>> a == toml.loads(toml.dumps(a))
True

Sorry for the delay in my response.

**Comment by dholth** [comment]
Whichever I installed from pypi at the time 
On Jul 4, 2016 22:20, W Pearson <notifications@github.com> wrote:If you incorrectly quote the key, the value which is getting parsed is garbage which results in the parser exhausting its options for determining what type of value it got. The last type of value which gets parsed is a date or number, hence the error message which you saw.

Which version of toml are you using? I get:

>>> import toml
>>> a = {'foo=bar': ['sdl2_lib']}
>>> a == toml.loads(toml.dumps(a))
True

Sorry for the delay in my response.
