### ISSUE TITLE
TOML emitter is wrong?

### ISSUE THREAD

**Issue by plombardi89** [uiri/toml#60]
This seems incorrect:

``` python
>>> import toml
>>> m = {'a': {}, 'b': {}}
>>> toml.dumps(m)
''
```

I would have expected:

```
[a]

[b]

```

I'm not super familiar with all the edge cases of the TOML format so perhaps this is expected, but it seems weird to say a Map of Empty Map's becomes equivalent to empty string.

**Comment by gwerbin** [comment]
Agreed, this seems counterintuitive.
