### ISSUE TITLE
floats with exponents outputted with leading 0s

### ISSUE THREAD

**Issue by DrRibosome** [uiri/toml#63]
Floats with exponents with leading `0`s (such as `1e-05`) are outputted with the leading `0` still attached, which is apparently not allowed under a strict interpretation of the toml spec. Float exponent fields are int fields, which are not allowed to have leading `0`s.

The problem comes from other toml parsers which take this (too?) seriously (for instance https://github.com/alexcrichton/toml-rs) and fail to load output generated by this lib

Is there any easy way to override the default formatting for a certain type?

**Comment by jdc2172** [comment]
Never mind, it seems simply making a wrapper object with the appropriate `__str__` method works

For example:
```
class FloatWrapper:
    def __init__(self, v):
        self.v = v
    def __str__(self):
        return '{0:.10f}'.format(self.v)
```
