### ISSUE TITLE
New lines in multi-line literal strings trimmed incorrectly

### ISSUE THREAD

**Issue by SergioBenitez** [uiri/toml#68]
The library is incorrectly parsing/generating code from multi-line literal strings by condensing multiple new lines in the string into a single one.

Example:

**EXPECTED:**

```python
import toml
toml.loads("a = '''\nhello\nworld\n\n\nbye'''")
{u'a': u'hello\nworld\n\nbye'}
```

**ACTUAL:**

```python
import toml
toml.loads("a = '''\nhello\nworld\n\n\nbye'''")
{u'a': u'hello\nworld\nbye'}
```

We expect two new lines between `world` and `bye`, but we get one. According to the specification (emphasis mine):

> Multi-line literal strings are surrounded by three single quotes on each side and allow newlines. Like literal strings, there is no escaping whatsoever. A newline immediately following the opening delimiter will be trimmed. **All other content between the delimiters is interpreted as-is without modification.**

I'll take a look at the code and propose a fix.

**Comment by SergioBenitez** [comment]
It looks like there's a test that contradicts the specification in @BurntSushi's tests. In particular, [this test](https://github.com/BurntSushi/toml-test/blob/master/tests/valid/multiline-string.toml#L12) with [this expected result](https://github.com/BurntSushi/toml-test/blob/master/tests/valid/multiline-string.json#L22). @avakar doesn't have a test case for this. I've fixed this issue in the Python script and will submit a PR. I believe @BurntSushi's test case is incorrect.

**Comment by uiri** [comment]
From the spec:

> For writing long strings without introducing extraneous whitespace, use a "line ending backslash". When the last non-whitespace character on a line is a `\`, it will be trimmed along with all whitespace (including newlines) up to the next non-whitespace character or closing delimiter.

Closing as WONTFIX due to compliance with the spec.

**Comment by SergioBenitez** [comment]
@uiri That line of the spec is entirely irrelevant to this issue.

**Comment by noqqe** [comment]
@uiri I totally aggree with @SergioBenitez

**Comment by uiri** [comment]
I'm sorry. You're right; it is relevant to the associated PR(s) but not to this issue.
