### ISSUE TITLE
Any plan on supporting local date and local time?

### ISSUE THREAD

**Issue by junjchen** [uiri/toml#73]
Hi,

Seems there is not current support on [Local Time](https://github.com/toml-lang/toml#local-time) and [Local Date](https://github.com/toml-lang/toml#local-date), are those on the plan?

**Comment by uiri** [comment]
Once there is a new toml version, I will add them. Right now those features are part of the latest version of the spec but not the latest release of 0.4.0

https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md

**Comment by uiri** [comment]
PR #105 adds support for Local Time.

**Comment by newtux** [comment]
There doesn't seem to be any movement in the toml repository on actually releasing a new version of the spec (ex of updating the main readme). 

Would you accept a PR for Local Date? Or is this a non starter until the "official" release spec is updated? As far as I can tell it is a fairly mixed bag among parsers of whether they stick with the readme in master or the official release spec.

**Comment by alecloudenback** [comment]
Looks like 0.5.0 includes this now? https://github.com/toml-lang/toml/blob/master/CHANGELOG.md
