### ISSUE TITLE
Python 3 compatibility 

### ISSUE THREAD

**Issue by francois2metz** [uiri/toml#8]
toml is not compatible with python 3.

There is at least _xrange_ which is not available.

```
NameError: global name 'xrange' is not defined
```

**Comment by Croydon** [comment]
@uiri I don't want to open a new issue just for asking that....

Is toml fully Python 3 compatible right now? If yes, could you please add a note to the readme or some other place, which is easy to find?

**Comment by uiri** [comment]
Yes, it is fully Python 2 & Python 3 compatible right now and shall remain that way for the foreseeable future. Continuous integration currently runs on Python 2.6, 2.7, 3.3, 3.4, 3.5, and 3.6.

I've added relevant classifiers to PyPI and a badge to the README although I'm not sure how long it will take the badge to update the info from PyPI.

**Comment by Croydon** [comment]
Thanks!
