### ISSUE TITLE
Ordering dumps

### ISSUE THREAD

**Issue by daviskirk** [uiri/toml#89]
At the moment dumps does not care about the order of the items in the passed dictionary.  However, when passing an ordered mapping like ``collections.OrderedDictionary`` it should probably try to preserve the order order in the outputted string as well.

**Comment by uiri** [comment]
Thanks for the issue report.

According to the [spec](https://github.com/toml-lang/toml#table), a table can only be written to once. Take for instance the following OrderedDict snippet:

```python
from collections import OrderedDict

d = OrderedDict()
d['a'] = OrderedDict()
d['a']['b'] = 1
d['a']['c'] = OrderedDict()
d['a']['c']['d'] = 2
d['a']['c']['e'] = 3
d['a']['f'] = 4
```

Strictly following the order in the passed dictionary would result in the following _invalid_ toml output:

```toml
[a]
b = 1
[a.c]
d = 2
e = 3
[a]
f = 4
```

The corresponding valid toml would be:

```toml
[a]
b = 1
f = 4
[a.c]
d = 2
e = 3
```

For that reason, `dumps` writes key-value pairs first and then writes out inner tables. The spec makes no guarantees about the ordering of keys within a table; I think that `toml.dumps(o)` consistently returning the same string for a given dictionary `o` is enough for order preservation.

Please feel free to re-open this issue if you feel that I have not adequately addressed your concern.
