### ISSUE TITLE
Exception is too broad.

### ISSUE THREAD

**Issue by Fatekiller23** [uiri/toml#92]
hi, i get this Exception when i use a wrong port number.
`influxdb.exceptions.InfluxDBClientError: 400: Bad request syntax ('new_issueline msg="Right Vertical Drive Fault" 1492937769000000')
`
this make me confused,because my request syntax is not wrong.
So, how about narrow the exception?

**Comment by uiri** [comment]
Hi Marshall,

> `influxdb.exceptions.InfluxDBClientError: 400: Bad request syntax ('new_issueline msg="Right Vertical Drive Fault" 1492937769000000')
> `
> this make me confused,because my request syntax is not wrong.
> So, how about narrow the exception?

This looks like an error in another library/project.

This repository is for the python library implementing the toml config language. It does not have anything to do with "influxdb". Sorry, I am not even sure what "influxdb" is (other than, most likely, a database of some sort).

I am closing this as WONTFIX. Please feel free to re-open it if you can point out the actual behaviour of the library, along with what you feel the proper behaviour should be.

**Comment by Fatekiller23** [comment]
sorry， my fault 😄
