### ISSUE TITLE
IndexError is sometimes raised

### ISSUE THREAD

**Issue by idmit** [uiri/toml#94]
Example:
```toml
a =
```

When `load` is called on a file like that, it fails with `IndexError: string index out of range`. This may not be the best behaviour, because
- it requires to write a very broad `except` clause;
- the exception itself doesn't really tell anything useful about what's wrong.

Is there something that should/can be done about this? Thanks! 👍

**Comment by uiri** [comment]
Thanks for the bug report!

I believe that the latest commit on master fixes this issue. The pre-parsing checks now pass empty vaues along to the value parsing code which raises a TomlDecodeError if it encounters an empty value.
